### ISSUE TITLE
java.lang.IllegalArgumentException: pullOffset should between 0 and 1!stretch 542

### ISSUE THREAD

**Issue by onecoders** [THEONE10211024/WaterDropListView#4]
FATAL EXCEPTION: main
                                                                        Process: com.neusmart.yunxueche, PID: 32272
                                                                        java.lang.IllegalArgumentException: pullOffset should between 0 and 1!stretch 542
                                                                            at com.neusmart.common.view.waterdroplistview.WaterDropListViewHeader.setVisiableHeight(WaterDropListViewHeader.java:178)
                                                                            at com.neusmart.common.view.waterdroplistview.WaterDropListView.updateHeaderHeight(WaterDropListView.java:197)
                                                                            at com.neusmart.common.view.waterdroplistview.WaterDropListView.updateHeaderHeight(WaterDropListView.java:202)
                                                                            at com.neusmart.common.view.waterdroplistview.WaterDropListView.onTouchEvent(WaterDropListView.java:281)
                                                                            at android.view.View.dispatchTouchEvent(View.java:9294)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                            at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                            at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                            at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by THEONE10211024** [comment]
多谢反馈，我会找时间修复一下

**Comment by QuentinLew** [comment]
似乎还没有修复啊,为了赶工自己强行把WaterDropListViewHeader#setVisiableHeight改成这样了..
`if(pullOffset<0){
    pullOffset=0;
}else if(pullOffset>1){
    pullOffset=1;
}`

这段应该是UI相关的吧

**Comment by THEONE10211024** [comment]
@QuentinLewes 实在抱歉，一直太忙了，你要是发现问题的话欢迎pull Request
